In [1]:
import qml 

In [2]:
from glob import glob
import numpy as np

In [21]:
database_xyzs = sorted(glob("../qm7/xyz/*.xyz"))

In [22]:
database_xyzs

['../qm7/xyz/qm7_0.xyz',
 '../qm7/xyz/qm7_1.xyz',
 '../qm7/xyz/qm7_10.xyz',
 '../qm7/xyz/qm7_100.xyz',
 '../qm7/xyz/qm7_1000.xyz',
 '../qm7/xyz/qm7_1001.xyz',
 '../qm7/xyz/qm7_1002.xyz',
 '../qm7/xyz/qm7_1003.xyz',
 '../qm7/xyz/qm7_1004.xyz',
 '../qm7/xyz/qm7_1005.xyz',
 '../qm7/xyz/qm7_1006.xyz',
 '../qm7/xyz/qm7_1007.xyz',
 '../qm7/xyz/qm7_1008.xyz',
 '../qm7/xyz/qm7_1009.xyz',
 '../qm7/xyz/qm7_101.xyz',
 '../qm7/xyz/qm7_1010.xyz',
 '../qm7/xyz/qm7_1011.xyz',
 '../qm7/xyz/qm7_1012.xyz',
 '../qm7/xyz/qm7_1013.xyz',
 '../qm7/xyz/qm7_1014.xyz',
 '../qm7/xyz/qm7_1015.xyz',
 '../qm7/xyz/qm7_1016.xyz',
 '../qm7/xyz/qm7_1017.xyz',
 '../qm7/xyz/qm7_1018.xyz',
 '../qm7/xyz/qm7_1019.xyz',
 '../qm7/xyz/qm7_102.xyz',
 '../qm7/xyz/qm7_1020.xyz',
 '../qm7/xyz/qm7_1021.xyz',
 '../qm7/xyz/qm7_1022.xyz',
 '../qm7/xyz/qm7_1023.xyz',
 '../qm7/xyz/qm7_1024.xyz',
 '../qm7/xyz/qm7_1025.xyz',
 '../qm7/xyz/qm7_1026.xyz',
 '../qm7/xyz/qm7_1027.xyz',
 '../qm7/xyz/qm7_1028.xyz',
 '../qm7/xyz/qm7_1029.xyz',
 '.

In [23]:
database_mols = [qml.Compound(x) for x in database_xyzs]

In [24]:
def get_ncharges_coords(mol):
    ncharges = mol.nuclear_charges
    heavy_ints = [i for i,x in enumerate(ncharges) if x!=1]
    heavy_ncharges = [ncharges[i] for i in heavy_ints]
    coords = mol.coordinates
    heavy_coords = [coords[i] for i in heavy_ints]
    return heavy_ncharges, heavy_coords

In [25]:
ncharges = [x.nuclear_charges for x in database_mols]

In [26]:
mbtypes=qml.representations.get_slatm_mbtypes([[6,7,8,16]])

In [27]:
def get_rep(mol, mbtypes):
    ncharges, coords = get_ncharges_coords(mol)
    rep = np.array(qml.representations.generate_slatm(coords, ncharges, 
                                            mbtypes, local=True))
    return ncharges, rep

In [28]:
# pad size is based on largest target 

In [29]:
database_ncharges = []
database_reps = []
for mol in database_mols:
    ncharge, rep = get_rep(mol, mbtypes)
    database_ncharges.append(ncharge)
    database_reps.append(rep)

In [30]:
database_reps = np.array(database_reps)

/home/puck/anaconda3/envs/aqml/lib/python3.7/site-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


In [31]:
database_labels = [t.split("/")[-1].split(".xyz")[0] for t in database_xyzs]

In [32]:
database_labels = np.array(database_labels)

In [33]:
database_ncharges = np.array(database_ncharges)

/home/puck/anaconda3/envs/aqml/lib/python3.7/site-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


In [34]:
np.savez("../representations/database_SLATM.npz", 
         database_labels=database_labels, 
         database_reps=database_reps,
        database_ncharges=database_ncharges)

In [35]:
database_ncharges

array([list([6]), list([6, 6]), list([6, 6, 6]), ...,
       list([6, 6, 6, 8, 6, 7]), list([6, 6, 6, 8, 6, 7]),
       list([6, 6, 6, 8, 6, 7])], dtype=object)

In [36]:
database_reps

array([array([[0., 0., 6., ..., 0., 0., 0.]]),
       array([[0., 0., 6., ..., 0., 0., 0.],
       [0., 0., 6., ..., 0., 0., 0.]]),
       array([[0., 0., 6., ..., 0., 0., 0.],
       [0., 0., 6., ..., 0., 0., 0.],
       [0., 0., 6., ..., 0., 0., 0.]]),
       ...,
       array([[0., 0., 6., ..., 0., 0., 0.],
       [0., 0., 6., ..., 0., 0., 0.],
       [0., 0., 6., ..., 0., 0., 0.],
       [8., 0., 0., ..., 0., 0., 0.],
       [0., 0., 6., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]]),
       array([[0., 0., 6., ..., 0., 0., 0.],
       [0., 0., 6., ..., 0., 0., 0.],
       [0., 0., 6., ..., 0., 0., 0.],
       [8., 0., 0., ..., 0., 0., 0.],
       [0., 0., 6., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]]),
       array([[0., 0., 6., ..., 0., 0., 0.],
       [0., 0., 6., ..., 0., 0., 0.],
       [0., 0., 6., ..., 0., 0., 0.],
       [8., 0., 0., ..., 0., 0., 0.],
       [0., 0., 6., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])], dtype=object)